In [1]:
#example of a one hot encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
#define data
data = asarray([['red'],['green'],['blue']])
print(data)
#define one hot encoding
encoder = OneHotEncoder(sparse_output=False)
#transform  data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
